### ISSUE TITLE
Update groupId?

### ISSUE THREAD

**Issue by Tobias-Ternent** [PRIDE-Utilities/ols-client#1]
Currently the groupid is listed as:
` <groupId>uk.ac.ebi.ols</groupId>`
Should we change this to be in-line with the other PRIDE-Utilities libraries?
` <groupId>uk.ac.ebi.pride.utilities</groupId>`

**Comment by ypriverol** [comment]
@Tobias-Ternent Great Idea, this is actually not anymore the previous tool and can cause a lot of issues. I will ask to Harald and let you know.
