### ISSUE TITLE
cannot find ols-client by maven coordinates

### ISSUE THREAD

**Issue by mglont** [PRIDE-Utilities/ols-client#16]
Hi,

Have any recent versions of ols-client been pushed to the [EBI Maven Repo](http://www.ebi.ac.uk/intact/maven/nexus/index.html#nexus-search;quick~ols-client)? I cannot seem to find them.

There's also a small typo in the README file in the "Maven Dependency" section at the bottom of the page -- there's an extraneous `>` in `<groupId>>uk.ac.ebi.pride.utilities</groupId>`.

Thanks,
Mihai.

**Comment by noedelta** [comment]
Hi Mihai,

We (IntAct + PRIDE) are moving the dependencies to a new  a better managed EBI Maven repo. I guess you should be able to find [here](http://www.ebi.ac.uk/Tools/maven/repos/) the latest release. For maven the configuration of the repo are

        <repository>
            <id>nexus-ebi-release-repo</id>
            <url>http://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/</url>
        </repository>
        <repository>
            <id>nexus-ebi-snapshot-repo</id>
            <url>http://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-snapshots/</url>
        </repository>

Regards,

Noe

**Comment by mglont** [comment]
Hi Noe,

Thanks, that's very useful.

Best,
Mihai.
