### ISSUE TITLE
maven install cannot generate javadoc with java 7

### ISSUE THREAD

**Issue by mglont** [PRIDE-Utilities/ols-client#17]
Relevant snippet of the log:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project ols-client: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - javadoc: error - invalid flag: -Xdoclint:none

it all works fine with java 1.8

is java 1.8 an absolute prerequisite for using the API?

Thanks,
Mihai.

**Comment by ypriverol** [comment]
No, you can deploy the library using the version 1.7. This is an dummy error in java 8 generating the javadoc. Please you can remove the flag -Xdoclient:none and deploy the library perfectly fine.

**Comment by mglont** [comment]
this is what I did in the end, thanks!

if you have time, maybe you can set up a Maven build profile[1] that is 
only triggered for Java 8.

thanks again,

mihai.

[1] 
https://maven.apache.org/guides/introduction/introduction-to-profiles.html

**Comment by ypriverol** [comment]
Hi @mglont: I will do it. Out of the topic, we have been thinking about a short publication of the ols-client and ols dialog our java desktop application to connect to OLS and I'm collecting all the services and tools that currently use the library. Can you send me your tool or tools to add them?

**Comment by Tobias-Ternent** [comment]
@ypriverol and @mglont  I think it would be best to fix the bad Javadoc itself which is wrong, that's causing the need for the -Xdoclint:none flag when using Java 8, which by default doesn't allow Javadoc without the correct syntax. If the Javadoc is fixed, then the flag can be removed and this will package fine for both Java 7 and 8., so no need to have build profiles per Java version.

From having a quick look at the Javadoc, there's syntax which is wrong, but also descriptions that are out of date. I can help to go through this and make the necessary changes soon.

**Comment by mglont** [comment]
Hi Yasset,

You can add BioModels to your user list. Logos are available at

http://www.ebi.ac.uk/biomodels/icons/BioModels_Database_logo_small.png

http://www.ebi.ac.uk/biomodels/icons/BioModels_Database_logo_large.png

Good luck with the publication!

Cheers,

Mihai.

**Comment by mglont** [comment]
that sounds like the best way forward, Tobias. thanks, -- mihai.

**Comment by Tobias-Ternent** [comment]
@mglont No problem: I've just pushed my changes to Master. The Javadoc syntax has been fixed, and the -Xdoclint:none config has been removed, so you should be good now for the future!

**Comment by ypriverol** [comment]
Great @Tobias-Ternent I will close this issue.
