### ISSUE TITLE
All maven repositories unreachable

### ISSUE THREAD

**Issue by matthiaskoenig** [PRIDE-Utilities/ols-client#18]
Hi all,
Since the EBI server maintenance/problems last week all ols-client maven repositories are offline and unreachable. It is impossible to build depending applications (I don't have this cached and cannot find any mirror on the web)

This affects the release and snapshot repositories.
```
<!-- EBI repo -->
<repository>
    <id>nexus-ebi-repo</id>
    <name>The EBI internal repository</name>
    <url>http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/</url>
    <releases>
    </releases>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
</repository>
```
I am working with the SNAPSHOTS, so the following is more important for me
```
 <repository>
            <id>EBI SNAPSHOT</id>
            <name>EBI Snapshot repository</name>
            <url>http://www.ebi.ac.uk/Tools/maven/repos/content/repositories/pst-snapshots</url>
        </repository>
```
The best
Matthias

**Comment by Tobias-Ternent** [comment]
Yes, the EBI Nexus is still down. I currently don't have an estimation for when it will be back up, sorry. Apparently the maintenance caused some hardware to fail, and it had to be replaced. Full systems restoration is likely not going to be within a matter of days, but potentially weeks .

**Comment by matthiaskoenig** [comment]
I understand.
As a workaround I could build the latest ols-client which makes it available in the local repository.
```
git clone https://github.com/PRIDE-Utilities/ols-client.git
mvn clean install
```
I hope I will find similar solutions for the other EBI libraries.

Perhaps it would be a good idea for the future to mirror maven releases in some central facility like maven central or mvnrepository.

**Comment by ypriverol** [comment]
@matthiaskoenig The repos are now but and we are sorry for the inconvenience. In the future, we plan to have a better backup system.
