### ISSUE TITLE
Slow performance, e.g. NCBItaxon, EFO

### ISSUE THREAD

**Issue by Tobias-Ternent** [PRIDE-Utilities/ols-client#2]
I've been testing the OLS-Dialog and it seems that trying to use large (or all) ontologies takes way too long.

E.g Selecting the NCBI taxonomy ontology (ncbitaxon) from OLS-Dialog, turns out that it has 1.4 million terms. OLS-client will retrieve all terms through the new WS, 1000 terms at a time, and each query takes about 10 seconds to return. This means it will take nearly 4 hours to obtain all the terms before anything else can be done, which is an unacceptable level of slow performance.

Repeating this with a smaller ontollogy, e.g. EFO which has almot 18 k terms, this completed in >30 seconds (about 2 seconds per 1000 terms query). This also feels like a less than acceptable level of performance.

Is there a better strategy we can approach this, @ypriverol ? Perhaps we need to ask for OLS itself to support different ways to query?

**Comment by ypriverol** [comment]
@Tobias-Ternent is this in the browser or the term search?

**Comment by Tobias-Ternent** [comment]
When selecting the ontology from OLS-dialog, here's the debug output for the 1st query that gets fired off (that will need to be iterated over 1400 pages:

> 08:59:07.271 [AWT-EventQueue-0] DEBUG org.springframework.web.client.RestTemplate - Created GET request for "http://snarf.ebi.ac.uk:8980/ols-beta/api/ontologies/ncbitaxon/terms/?page=0&size=1000"
08:59:07.271 [AWT-EventQueue-0] DEBUG org.springframework.web.client.RestTemplate - Setting request Accept header to [application/json, application/*+json]
08:59:15.640 [AWT-EventQueue-0] DEBUG org.springframework.web.client.RestTemplate - GET request for "http://snarf.ebi.ac.uk:8980/ols-beta/api/ontologies/ncbitaxon/terms/?page=0&size=1000" resulted in 200 (OK)
08:59:15.640 [AWT-EventQueue-0] DEBUG org.springframework.web.client.RestTemplate - Reading [class uk.ac.ebi.pride.utilities.ols.web.service.model.TermQuery] as "application/json;charset=UTF-8" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@79b365be]
08:59:15.890 [AWT-EventQueue-0] DEBUG org.springframework.web.client.RestTemplate - Created GET request for "http://snarf.ebi.ac.uk:8980/ols-beta/api/ontologies/ncbitaxon/terms/?page=1&size=1000"
08:59:15.891 [AWT-EventQueue-0] DEBUG org.springframework.web.client.RestTemplate - Setting request Accept header to [application/json, application/*+json]

**Comment by ypriverol** [comment]
@Tobias-Ternent the way that OLS is implemented will not allow us to do more. I guess the best way is improving the OLS-Dialog. When OLS dialog is loading an ontology it looks for all the root terms and the first children of them. I think we can improve that, the other way is by improving the step. In the current output I saw two queries that are the same and can be summarise only in one.

**Comment by Tobias-Ternent** [comment]
Yes, that's likely the best way forward then, change the behaviour in ols-dialog. I was going to raise this issue on that repo, but I didn't see the option anywhere to...and now I've enabled issues on it :)

**Comment by Tobias-Ternent** [comment]
Fixed in ols-dialog.
