### ISSUE TITLE
Inconsistent (?) results from query, no wildcard?

### ISSUE THREAD

**Issue by Tobias-Ternent** [PRIDE-Utilities/ols-client#3]
When querying, inconsistent results seem to be returned, e.g. for the BRENDA tissue ontology BTO, quering for the term name "test" returns no results:
http://snarf.ebi.ac.uk:8980/ols-beta/api/search?q=*test*&queryFields=label,synonyms&rows=100&start=0&ontology=bto
But querying for "testis" returns 4 results:
http://snarf.ebi.ac.uk:8980/ols-beta/api/search?q=*testis*&queryFields=label,synonyms&rows=100&start=0&ontology=bto

Is a wildcard not being applied, or used, properly before and after the term name? Does the new OLS support querying for a term name using wildcards? I couldn't find mention of this on the API page: http://www.ebi.ac.uk/ols/beta/docs/api

**Comment by ypriverol** [comment]
@Tobias-Ternent can you test the current version. I just did a commit to solve the issue.

**Comment by ypriverol** [comment]
Problem solve. +1
