### ISSUE TITLE
OLS query fails

### ISSUE THREAD

**Issue by Tobias-Ternent** [PRIDE-Utilities/ols-client#4]
As of this week all the ols-client unit tests are failing with this message:
`org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class uk.ac.ebi.pride.utilities.ols.web.service.model.TermQuery] and content type [application/json;charset=UTF-8]`

e.g.
```
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:107)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:518)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:473)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:238)
	at uk.ac.ebi.pride.utilities.ols.web.service.client.OLSClient.isObsolete(OLSClient.java:476)
```

**Comment by ypriverol** [comment]
@Tobias-Ternent are you planning to take this issue?. I can do it

**Comment by Tobias-Ternent** [comment]
Can you take a look please? I've tried to fix it by improving the TermsQuery class, but it doesn't seem to make any difference, so I'm probably missing something.

**Comment by ypriverol** [comment]
@Tobias-Ternent the current version of the OLS client is ready for the dev API, then we need to way until they move the current dev to prod. if you check in the test I'm using  `OLSWsConfigDev ` . We can ask to simon or the ols guys when they are planning to do the deploy, then we can move to `OLSWsConfigProd `

**Comment by Tobias-Ternent** [comment]
Just a reminder to us as discussed offline, we'll address this again when the new OLS beta moves into production properly, which is currently planned for late April.

**Comment by ypriverol** [comment]
+1

**Comment by ypriverol** [comment]
Problem solved
