### ISSUE TITLE
Equivalent for #getTermsByExactName()

### ISSUE THREAD

**Issue by tschaka1904** [PRIDE-Utilities/ols-client#6]
Dear PRIDE-Team, 

is there a equivalent for the method [#getTermsByExactName()](http://www.ebi.ac.uk/ontology-lookup/api/uk/ac/ebi/ols/web/interfaces/QueryImpl.html#getTermsByExactName(java.lang.String,%20java.lang.String))?

Thanks and best regards,
Max

**Comment by ypriverol** [comment]
Have you try https://github.com/PRIDE-Utilities/ols-client/blob/master/src/main/java/uk/ac/ebi/pride/utilities/ols/web/service/client/OLSClient.java#L386

**Comment by tschaka1904** [comment]
No not yet. I wasn't sure 'Partial', since I need the 'Exact'. But I'll give it a try.
