### ISSUE TITLE
Equivalent for #getTermRelations()

### ISSUE THREAD

**Issue by tschaka1904** [PRIDE-Utilities/ols-client#7]
Dear PRIDE-Team, 

is there a equivalent for the method [#getTermRelations()](http://www.ebi.ac.uk/ontology-lookup/api/uk/ac/ebi/ols/web/interfaces/QueryImpl.html#getTermRelations(java.lang.String,%20java.lang.String))?

Thanks and best regards,
Max

**Comment by ypriverol** [comment]
We need to look into the child functions because Simon told me that you can retrieve all the terms that are related with one particular term but is not implemented yet.
