### ISSUE TITLE
Equivalent for #getTermParents()

### ISSUE THREAD

**Issue by tschaka1904** [PRIDE-Utilities/ols-client#8]
Dear PRIDE-Team, 

is there a equivalent for the method [#getTermParents()](http://www.ebi.ac.uk/ontology-lookup/api/uk/ac/ebi/ols/web/interfaces/QueryImpl.html#getTermParents(java.lang.String,%20java.lang.String))?

Thanks and best regards,
Max

**Comment by ypriverol** [comment]
We don't have this functionality implemented we only have the child, however should be very easy because for every term you have the list of parents. I will try to look for sometime to implement this functionality. But feel free to do it if you want

**Comment by tschaka1904** [comment]
Thanks! I'll have a look and try to implement it.

**Comment by ypriverol** [comment]
+1
