### ISSUE TITLE
Equivalent for getTermMetadata()

### ISSUE THREAD

**Issue by tschaka1904** [PRIDE-Utilities/ols-client#9]
Dear PRIDE-Team, 

is there a equivalent for the method [#getTermMetadata()](http://www.ebi.ac.uk/ontology-lookup/api/uk/ac/ebi/ols/web/interfaces/QueryImpl.html#getTermMetadata(java.lang.String,%20java.lang.String))?

Thanks and best regards,
Max

**Comment by ypriverol** [comment]
We don't have any more this concept as I explain you before, then probably would be nice to have this function from the ols by talking with @simonhup or construct the metadata by using the information in other fields.

**Comment by tschaka1904** [comment]
Talking to @simonhup would be probably the the easiest. I'll try to get in contact with him.

**Comment by tschaka1904** [comment]
There is no proper replacement for it.

**Comment by ypriverol** [comment]
@tschaka1904 can we close this issue?
